### ISSUE TITLE
Payment status not updating

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware5#215]
I updated to the latest version (3.8.0) and now all my orders are not getting the right payment status
![image](https://user-images.githubusercontent.com/15035750/168787632-ecf6d658-36e5-4e29-8da4-96787c162e7d.png)
Even though the transaction is completed successfully
I get the following error in the core log
 
![image](https://user-images.githubusercontent.com/15035750/168788229-8a0abd77-7775-41a3-b9cb-8e90ea95d079.png)

**Comment by andydandy80** [comment]
We have the same error in plugin version 3.8.0 and shopware 5.7.10:

`PHP Fatal error:  Uncaught Enlight_Exception: Property "paymentResultCodeHandler" not found failure in /var/www/html/xxx/custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php:114
 Stack trace:
 #0 /var/www/html/xxx/custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php(114): Enlight_Class->__get()
 #1 /var/www/html/xxx/engine/Library/Enlight/Controller/Action.php(186): Shopware_Controllers_Frontend_Adyen->paymentDetailsAction()
 #2 /var/www/html/xxx/engine/Library/Enlight/Controller/Dispatcher/Default.php(467): Enlight_Controller_Action->dispatch()
 #3 /var/www/html/xxx/engine/Library/Enlight/Controller/Front.php(225): Enlight_Controller_Dispatcher_Default->dispatch()
 #4 /var/www/html/xxx/engine/Shopware/Kernel.php(197): Enlight_Controller_Front->dispatch()
 #5 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Shopware\\Kernel->handle()
 #6 /var/www/html/xxx/vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\\Component\\HttpKer in /var/www/html/xxx/custom/plugins/AdyenPayment/Controllers/Frontend/Adyen.php on line 114, referer: https://xxx.de/stage/de/checkout
`

**Comment by TaiKamilla** [comment]
@andydandy80 Did you find a solution?

**Comment by olga-adyen** [comment]
ok, i'll close this issue
