### ISSUE TITLE
Order with cart ID XYZ still not created

### ISSUE THREAD

**Issue by magnolia4** [Adyen/adyen-shopware5#234]
Plugin: 4.1.9
Shopware: 5.7.14

We now often have the problem that the payment process was carried out successfully with Adyen, but the order is not created correctly in Shopware. At first we thought it was just the EPS payment method. But now we also have a case with Sofortüberweisung.

In Shopware the order remains orphaned as canceled.

![image](https://github.com/Adyen/adyen-shopware5/assets/9446008/14f4e510-fae4-410d-b22d-e3efdd64cfcb)

![image](https://github.com/Adyen/adyen-shopware5/assets/9446008/9599aa25-f5d7-4cd9-b7fd-f83d1ea84288)

**This bug is very urgent because the shop customer makes a payment, but it is not available as an order in the shop and so he does not receive any goods.**

**Comment by sheitmeier** [comment]
I guess we have the same issue. The issue exists with different payment methods for us as well. We were able to track it down to the following call and the corresponding exception: Hope this information helps you to identify the cause:

**Request**

[14/Apr/2024:12:19:53 +0200] "GET /AdyenPaymentProcess/handleRedirect/signature/xxxletmeknowifthisisrelevant/reference/e484xxxletmeknowifthisisrelevantc1473220c1e3ce?redirectResult=X3XtfGC7%21H4sIAAAAAAAA%2F21SYW%2FaMBD9L%2F5MaOw4DxxxletmeknowifthisisrelevantcS4QkQTXcdBo1f8%2Bp6MaW%2Ff13bv37t3dC5IahIFsaFCIiEuo41IH0yV2Q8xDTNaohzRkhQZp5uJYQW1iYQQKX5CQT63F9VDKfVubSYZC7LPAZ14PiSwrTLGvRfnOVo3SkFuTOPm6WPL7LyT6lkQkItZgVwpdC%2FVbvuk30DS297GwiigTKQmkO3Ag8IhDUkEdLjh3hE9TmflUkoGHXq1j1Q3ROclWa6jl0TaPVomVP4iyBRR6Lgn8jqmKO9CdAwoZ76FUizqL9pmlnCaxPW%2BR9PEExyMLVaDlVtTmlNfCN0LLYauhXMJPU5SXVXo1im5vzrgJ5NAN04kAHdAsA9cFSnPOuBdITG0o4koMnqX00F4Xm8Iubd6o887ZzXw2Hc%2FZdTy%2BHkxjzzKVKBNo2tL8Q%2F3PdjU8tdCY4YeTvA85qQ1stOiKfXNUnUxkg1zfrpaPl6PZKJlEZ5HO2Yf3PSLGuyNoMK2uV7q0yNYY1YQPFw8Xcgtyt29Ns90rBdopiwP0RXaEui%2F31Yf6H%2BD0cMmb6ueNKrJPl%2FMhiYKxT2lAfR9ztxut2RX16VKqTfsH0o%2BXfhSs1yxZTKdXjJH%2B83X9dT3bsB%2BpuHfd8UgpM31aqXiyq%2FR3pg8xvVvkXvUcLFZ%2FBZkLLaqm25Z%2BW7e1aFop7YdaX7PfQRfeYyn3PA87ASPcIdxPHY7dzMlk6hEfp3jAoVM1WkhQwt6q03Fdx74A4wMe2N4gzyXLvVQEuc%2FyFAuKCXGyAfYCkYsAiw4mjovR6y8SHRtdtQMAAA%3D%3D1Qd6JfFowp%2Byf58vzt1focLu5otie%2FONauISHZPjRrg%3D HTTP/1.0" 302 1218 "https://pay.klarna.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
[14/Apr/2024:12:19:53 +0200] "GET /checkout/shippingPayment HTTP/1.0" 200 66106 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"

**Exception**

[2024-04-14 12:19:53] adyen_payment.ERROR: ADYEN LOG: | Date: 14/04/2024 | Time: 12:19:53 | Log level: ERROR | Message: Unhandled error occurred. | Context data: ({"message":"Required field 'paymentData' is not provided.","type":"Adyen\\Core\\BusinessLogic\\AdyenAPI\\Exceptions\\HttpApiRequestException","trace":"#0 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdyenAPI\/Http\/Proxy.php(209): Adyen\\Core\\BusinessLogic\\AdyenAPI\\Exceptions\\HttpApiRequestException::fromErrorResponse(Object(Adyen\\Core\\Infrastructure\\Http\\HttpResponse))
#1 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdyenAPI\/Http\/Proxy.php(150): Adyen\\Core\\BusinessLogic\\AdyenAPI\\Http\\Proxy->validateResponse(Object(Adyen\\Core\\Infrastructure\\Http\\HttpResponse))
#2 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdyenAPI\/Http\/Proxy.php(90): Adyen\\Core\\BusinessLogic\\AdyenAPI\\Http\\Proxy->call('POST', Object(Adyen\\Core\\BusinessLogic\\AdyenAPI\\Checkout\\Payments\\Requests\\UpdatePaymentDetailsHttpRequest))
#3 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdyenAPI\/Checkout\/Payments\/Http\/Proxy.php(42): Adyen\\Core\\BusinessLogic\\AdyenAPI\\Http\\Proxy->post(Object(Adyen\\Core\\BusinessLogic\\AdyenAPI\\Checkout\\Payments\\Requests\\UpdatePaymentDetailsHttpRequest))
#4 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Domain\/Checkout\/PaymentRequest\/Services\/PaymentRequestService.php(103): Adyen\\Core\\BusinessLogic\\AdyenAPI\\Checkout\\Payments\\Http\\Proxy->updatePaymentDetails(Object(Adyen\\Core\\BusinessLogic\\Domain\\Checkout\\PaymentRequest\\Models\\UpdatePaymentDetailsRequest))
#5 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/CheckoutAPI\/PaymentRequest\/Controller\/PaymentRequestController.php(52): Adyen\\Core\\BusinessLogic\\Domain\\Checkout\\PaymentRequest\\Services\\PaymentRequestService->updatePaymentDetails(Object(Adyen\\Core\\BusinessLogic\\Domain\\Checkout\\PaymentRequest\\Models\\UpdatePaymentDetailsRequest))
#6 (internal function): Adyen\\Core\\BusinessLogic\\CheckoutAPI\\PaymentRequest\\Controller\\PaymentRequestController->updatePaymentDetails(Array)
#7 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Bootstrap\/Aspect\/Aspects.php(82): call_user_func_array(Array, Array)
#8 (internal function): Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\Aspects->Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\{closure}()
#9 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Domain\/Multistore\/StoreContext.php(54): call_user_func_array(Object(Closure), Array)
#10 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdminAPI\/Aspects\/StoreContextAspect.php(30): Adyen\\Core\\BusinessLogic\\Domain\\Multistore\\StoreContext::doWithStore('1', Object(Closure), Array)
#11 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Bootstrap\/Aspect\/CompositeAspect.php(41): Adyen\\Core\\BusinessLogic\\AdminAPI\\Aspects\\StoreContextAspect->applyOn(Object(Closure), Array)
#12 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Bootstrap\/Aspect\/CompositeAspect.php(47): Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\CompositeAspect->applyOn(Object(Closure), Array)
#13 (internal function): Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\CompositeAspect->Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\{closure}()
#14 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/AdminAPI\/Aspects\/ErrorHandlingAspect.php(26): call_user_func_array(Object(Closure), Array)
#15 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Bootstrap\/Aspect\/CompositeAspect.php(41): Adyen\\Core\\BusinessLogic\\AdminAPI\\Aspects\\ErrorHandlingAspect->applyOn(Object(Closure), Array)
#16 \/custom\/plugins\/AdyenPayment\/vendor\/adyen\/integration-core\/src\/BusinessLogic\/Bootstrap\/Aspect\/Aspects.php(83): Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\CompositeAspect->applyOn(Object(Closure))
#17 \/custom\/plugins\/AdyenPayment\/Controllers\/Frontend\/AdyenPaymentProcess.php(313): Adyen\\Core\\BusinessLogic\\Bootstrap\\Aspect\\Aspects->__call('updatePaymentDe...', Array)
#18 \/custom\/plugins\/AdyenPayment\/Controllers\/Frontend\/AdyenPaymentProcess.php(202): Shopware_Controllers_Frontend_AdyenPaymentProcess->handleAdditionalDataAndGetRedirectUrl(Array)
#19 \/vendor\/shopware\/shopware\/engine\/Library\/Enlight\/Controller\/Action.php(192): Shopware_Controllers_Frontend_AdyenPaymentProcess->handleRedirectAction()
#20 \/vendor\/shopware\/shopware\/engine\/Library\/Enlight\/Controller\/Dispatcher\/Default.php(478): Enlight_Controller_Action->dispatch('handleRedirectA...')
#21 \/vendor\/shopware\/shopware\/engine\/Library\/Enlight\/Controller\/Front.php(228): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#22 \/vendor\/shopware\/shopware\/engine\/Shopware\/Kernel.php(188): Enlight_Controller_Front->dispatch()
#23 \/vendor\/symfony\/http-kernel\/HttpCache\/SubRequestHandler.php(102): Shopware\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 \/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php(453): Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler::handle(Object(AppKernel), Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 \/vendor\/shopware\/shopware\/engine\/Shopware\/Components\/HttpCache\/AppCache.php(261): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true, NULL)
#26 \/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php(426): Shopware\\Components\\HttpCache\\AppCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true)
#27 \/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php(317): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->fetch(Object(Symfony\\Component\\HttpFoundation\\Request), true)
#28 \/vendor\/shopware\/shopware\/engine\/Shopware\/Components\/HttpCache\/AppCache.php(188): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->lookup(Object(Symfony\\Component\\HttpFoundation\\Request), true)
#29 \/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php(192): Shopware\\Components\\HttpCache\\AppCache->lookup(Object(Symfony\\Component\\HttpFoundation\\Request), true)
#30 \/vendor\/shopware\/shopware\/engine\/Shopware\/Components\/HttpCache\/AppCache.php(113): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 \/shopware.php(30): Shopware\\Components\\HttpCache\\AppCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#32 {main}"})  [] {"uid":"d13e38c"}

**Comment by magnolia4** [comment]
@teodoratimoti Can you please provide us a status on this issue?

**Comment by magnolia4** [comment]
@logeecom We urgently need feedback on this.

**Comment by logeecom** [comment]
Hello @magnolia4,

Thank you for reaching out to us regarding this issue. We apologize for the late reply.

Please note that our team has attempted to reproduce the reported issue in a local environment (using the same payment methods, system, and plugin versions), but without success.

We can advise you to upgrade the plugin version to the latest one ([4.1.10](https://github.com/Adyen/adyen-shopware5/releases/tag/4.1.10)) and check if the issue persists.

If the issue is still present even after the upgrade, our team would need to log into the shop for further investigation. However, we strongly advise against sharing your shop credentials through GitHub due to security concerns. There is an established procedure regarding credentials sharing with us.

For more information about the procedure and to proceed further with the investigation, please reach out to [support@adyen.com](mailto:support@adyen.com) (https://www.adyen.help/hc/en-us/requests/new) or you can submit your request through the Support section of your Adyen Customer Area. Note that you will reach the 1st line of support, after which they will direct you to us (second line of support). You can also mention that you opened a GitHub ticket and that Logeecom directed you to Adyen support (for further investigation in your shop.)

Please describe your issue in as much detail as you can and our teams will review it.

If you have any questions or concerns, feel free to let us know.

Thank you,

Kind regards.

**Comment by sheitmeier** [comment]
Hi guys, just wondering: Have you found a cause for the issue?

**Comment by magnolia4** [comment]
As I mentioned earlier, the problem is sporadic. But the problem has to be somewhere.
